columnSuffix: null
contentColumnType: string
fieldGroup: fe349c76-25d4-43c8-976b-a5a4bc06ae8f # About
handle: aboutSkills
instructions: ''
name: Skills
searchable: false
settings:
  contentTable: '{{%matrixcontent_aboutskills}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
