columnSuffix: null
contentColumnType: string
fieldGroup: 2be95b78-fbc5-4763-bfd2-4619b0b66d4d # Blog
handle: blogStyles
instructions: ''
name: Styles
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: 'group:3d401dcb-d778-46a7-93b4-55bbdd32c55b' # Styles
  sources: '*'
  targetSiteId: null
  validateRelatedElements: true
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
