columnSuffix: bjdlwalo
contentColumnType: string(255)
fieldGroup: ca1d3a60-da6a-4956-80c7-3150c907e359 # Social media
handle: instagramUrl
instructions: ''
name: 'Instagram URL'
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
