fieldLayouts:
  24281711-964a-46b7-9ab6-4e045cbf3222:
    tabs:
      -
        elements:
          -
            fieldUid: 64e60612-12fa-462b-a5ad-8a841ede300d # Facebook URL
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 224db3c1-d4a7-49cd-988f-9d41b09fa283 # Instagram URL
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ade72aeb-22f0-4031-b309-bb397f123ca8 # Twitter URL
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: socialmedia
name: 'Social Media'
sortOrder: 1
